# Generated by Django 5.1.4 on 2024-12-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id_destination", models.AutoField(primary_key=True, serialize=False)),
                ("X", models.FloatField()),
                ("Y", models.FloatField()),
                ("nom_ville", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id_vehicule",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("immatriculation", models.CharField(max_length=20)),
                ("modele", models.CharField(max_length=100)),
                ("propulsion", models.CharField(max_length=50)),
                ("nombre_place", models.IntegerField()),
                ("autonomie_theorique", models.FloatField(blank=True, null=True)),
                ("taille_batterie", models.FloatField(blank=True, null=True)),
                ("conso_kwh_100", models.FloatField(blank=True, null=True)),
                ("conso_litre_100", models.FloatField(blank=True, null=True)),
                ("site_rattachement", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Planning_reservation",
            fields=[
                ("id_reservation", models.AutoField(primary_key=True, serialize=False)),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
                ("nombre_places_reservees", models.IntegerField()),
                ("nom_utilisateur", models.CharField(max_length=100)),
                (
                    "immatriculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flotte.voiture"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_debut"],
            },
        ),
    ]
